<?php

/**Author : Oladele John

** © 2022 Oladele John

** Web application

** File name : help/submit-feedback.php

** About : this module submits the user feed back form data

*/

/**PSUEDO ALGORITHM
 * *
 * define the submit feedback class
 * fetch the feed back data
 * sanitize the feed back data
 * define auto generated data
 * insert the feedbacks in the edtech feedback database
 * 
 * *
 */

//define the submit feedback class
class submitFeedback{

    public $email;

    public $feedback;


    public $sanitized_email;

    public $sanitized_feedback;

    
    public $date;

    public $time;


    //fetch the feed back data
    public function fetchFeedback(){

        $this->email = $_POST['email'];
        
        $this->feedback = $_POST['feedback'];

    }

    //sanitize the feed back data
    public function sanitize($connection,$data){

        $data = htmlspecialchars($data);
        $data = stripslashes($data);
        $data = strip_tags($data);
        $data = htmlentities($data);
        $data = $connection->real_escape_string($data);

        return $data; 

    }

    //define auto generated data
    public function defineAutoGeneratedData(){

        $this->date = date("Y/m/d");

        $this->time = date("h:i:sa");

    }

    //insert the feedbacks in the edtech feedback database
    public function insertIntoFeedbackDb(){

        //require the env library
        require('../vendorEnv/autoload.php');

        $user_db_conn_env = Dotenv\Dotenv::createImmutable(__DIR__, '../env/db-conn-var.env');
        $user_db_conn_env->load();

        // user db connection
        include('../resources/database/feedbacks-db-connection.php'); //conn17

        $insert_into_feedback_query = "INSERT INTO feedbacks 
        (
            email,feedbacks,date,time
        )
        VALUES(
            '$this->sanitized_email','$this->sanitized_feedback','$this->date','$this->time'
        )";

        if($conn17->query($insert_into_feedback_query)){

            header('location:index.php?alert=true');

        }

        mysqli_close($conn17);

    }

}

$submit_feedback = new submitFeedback();

if(!empty($_POST['email']) && !empty($_POST['feedback'])){

    $submit_feedback->fetchFeedback();

    //require the env library
    require('../vendorEnv/autoload.php');

    $user_db_conn_env = Dotenv\Dotenv::createImmutable(__DIR__, '../env/db-conn-var.env');
    $user_db_conn_env->load();

    // user db connection
    include('../resources/database/feedbacks-db-connection.php'); //conn17

    $submit_feedback->sanitized_email = $submit_feedback->sanitize($conn17,$submit_feedback->email);
    
    $submit_feedback->sanitized_feedback = $submit_feedback->sanitize($conn17,$submit_feedback->feedback);

    $submit_feedback->defineAutoGeneratedData();

    $submit_feedback->insertIntoFeedbackDb();

    mysqli_close($conn17);

}else{

    header('location:index.php?emptyAlert=true');

}

?>